name: Apply Terraform Configuration
on:
  push:
    branches:
      - main

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  validate-plan-apply:
    name: Terraform Validate, Plan, and Apply
    runs-on: ubuntu-latest
    env:
      GITHUB_OWNER: ukhomeoffice
      GITHUB_APP_ID: ${{ secrets.GH_APP_ID }}
      GITHUB_APP_INSTALLATION_ID: ${{ secrets.GH_APP_INSTALLATION_ID }}
      GITHUB_APP_PEM_FILE: ${{ secrets.GH_APP_PEM_FILE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ~1.7.0

      - name: Configure AWS IdP Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::850744974572:role/AWSA-GitHubTerraformAllState-Role
          role-session-name: GitHubActions
          retry-max-attempts: 5
          aws-region: eu-west-2

      - name: Terraform Init
        run: |
          terraform init -reconfigure \
          -backend-config="bucket=${{ secrets.TF_BUCKET }}" \
          -backend-config="region=eu-west-2"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Post failure to Slack channel
        uses: slackapi/slack-github-action@v1
        if: failure()
        with:
          channel-id: ${{ vars.SLACK_CHANNEL_ID }}
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Applying terraform from <https://github.com/UKHomeOffice/core-cloud-github-config|core-cloud-github-config> failed.\n\n Run ID: ${{ github.run_id }}-${{ github.run_number }}\nCommit SHA: ${{ github.sha }}"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Go to Job"
                    },
                    "value": "button_value",
                    "url": "https://github.com/UKHomeOffice/core-cloud-github-config/actions/runs/${{github.run_id}}/attempts/${{github.run_number}}",
                    "action_id": "button-action"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
