name: Validate Terraform
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  validate:
    if: github.event.pull_request.draft == false
    name: Validate Terraform
    runs-on: ubuntu-latest
    env:
      GITHUB_OWNER: ukhomeoffice
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ~1.6.0

      - name: Configure AWS Credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::850744974572:role/AWSA-GitHubTerraformConfigState-Role
          role-session-name: GitHubActions
          aws-region: eu-west-2
          retry-max-attempts: 5
          output-credentials: true

      - name: Terraform Init
        run: |
          terraform init -reconfigure \
          -backend-config="bucket=${{ secrets.TF_BUCKET }}" \
          -backend-config="region=eu-west-2" \
          -backend-config="access_key=${{ steps.aws-credentials.outputs.aws-access-key-id }}" \
          -backend-config="secret_key=${{ steps.aws-credentials.outputs.aws-secret-access-key }}"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan
